version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing packages
      - npm install
    build:
      - echo Creating build
      - npm run build
    post_build:
      - echo Removing unnecessary files
      - rm -rf node_modules/
artifacts:
  type: zip
  files:
    - package.json
    - package-lock.json
    - "dist/**/*"
