version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing packages
      - npm install
    build:
      - echo Creating build
      - npm run build
artifacts:
  base-directory: "."
  files:
    - "**/*"
